import test from 'node:test';
import assert from 'node:assert/strict';
import { completeMatch, determineWinner, getHeadToHead, getPairStats, getPlayerStats, getRoundProgress, reviseMatchResult, rotateLineup, undoLastMatch, validateLineup, type Lineup, type Session } from '../src/lib/domain';
const lineup:Lineup={A:['a','b'],B:['c','d'],bench:['e']};
const now='2026-10-01T18:00:00.000Z';
function session():Session{return {id:'night',title:'Test',date:'2026-10-01',startedAt:now,status:'active',playerIds:['a','b','c','d','e'],lineup:{A:['a','b'],B:['c','d'],bench:['e']},scoreA:0,scoreB:0,matchStartedAt:now,matches:[],version:1,updatedAt:now}}
test('winner handles normal, draws, and manual outcomes',()=>{assert.equal(determineWinner(3,2,'normal'),'A');assert.equal(determineWinner(1,4,'normal'),'B');assert.equal(determineWinner(2,2,'normal'),null);assert.equal(determineWinner(2,2,'penalties','B'),'B');assert.throws(()=>determineWinner(2,2,'penalties'));});
test('loser replacement preserves teammate and makes leaver next bench',()=>{const next=rotateLineup(lineup,'B','a');assert.deepEqual(next,{A:['e','b'],B:['c','d'],bench:['a']});assert.deepEqual(lineup,{A:['a','b'],B:['c','d'],bench:['e']});assert.throws(()=>rotateLineup(lineup,'B','c'));});
test('bench queue supports more than five participants',()=>{const next=rotateLineup({A:['a','b'],B:['c','d'],bench:['e','f']},'A','c');assert.deepEqual(next.bench,['f','c']);assert.deepEqual(next.B,['e','d']);});
test('draw or no bench keeps lineup',()=>{assert.deepEqual(rotateLineup(lineup,null),lineup);assert.deepEqual(rotateLineup({A:['a','b'],B:['c','d'],bench:[]},'A'),{A:['a','b'],B:['c','d'],bench:[]});});
test('lineup validation rejects duplicates and missing bench players',()=>{validateLineup(['a','b','c','d','e'],lineup);assert.throws(()=>validateLineup(['a','b','c','d','e'],{A:['a','a'],B:['c','d'],bench:['e']}));});
test('match completion records raw participants and undo restores score and lineup',()=>{const start={...session(),scoreA:3,scoreB:2};const done=completeMatch(start,{scoreA:3,scoreB:2,resultType:'normal',leavingPlayerId:'c'},'2026-10-01T18:20:00.000Z');assert.equal(done.matches[0].participants.length,4);assert.deepEqual(done.lineup,{A:['a','b'],B:['e','d'],bench:['c']});assert.equal(done.matches[0].winner,'A');const restored=undoLastMatch(done);assert.deepEqual(restored.lineup,start.lineup);assert.equal(restored.scoreA,3);assert.equal(restored.scoreB,2);assert.equal(restored.matches.length,0);});
test('editing a result clears its saved punchline while preserving the played lineup',()=>{const done=completeMatch(session(),{scoreA:3,scoreB:1,resultType:'normal',leavingPlayerId:'c'},'2026-10-01T18:20:00.000Z');const original={...done.matches[0],punchline:'בדיחה על 3:1',punchlineStyle:2};const edited=reviseMatchResult(original,1,4,'normal');assert.equal(edited.punchline,undefined);assert.equal(edited.punchlineStyle,undefined);assert.equal(edited.winner,'B');assert.equal(edited.scoreB,4);assert.deepEqual(edited.lineupBefore,original.lineupBefore);});
test('a pair completes a round only after beating every distinct opposing pair',()=>{let s=session();s=completeMatch(s,{scoreA:1,scoreB:0,resultType:'normal',leavingPlayerId:'c'});s=completeMatch(s,{scoreA:1,scoreB:0,resultType:'normal',leavingPlayerId:'d'});assert.deepEqual(getRoundProgress(s.matches).completed,[]);assert.equal(getRoundProgress(s.matches).beaten,2);s=completeMatch(s,{scoreA:1,scoreB:0,resultType:'normal',leavingPlayerId:'e'});const progress=getRoundProgress(s.matches);assert.equal(progress.completed.length,1);assert.deepEqual(progress.completed[0].pair,['a','b']);assert.equal(progress.beaten,0);assert.equal(progress.required,3);});
test('a draw interrupts a pairs round streak',()=>{let s=session();s=completeMatch(s,{scoreA:1,scoreB:0,resultType:'normal',leavingPlayerId:'c'});s=completeMatch(s,{scoreA:1,scoreB:0,resultType:'normal',leavingPlayerId:'d'});s=completeMatch(s,{scoreA:0,scoreB:0,resultType:'normal'});s=completeMatch(s,{scoreA:1,scoreB:0,resultType:'normal',leavingPlayerId:'e'});const progress=getRoundProgress(s.matches);assert.equal(progress.completed.length,0);assert.equal(progress.beaten,1);assert.equal(progress.required,3);});
test('pair, opponent and streak calculations use match history',()=>{let s=session();s=completeMatch(s,{scoreA:3,scoreB:1,resultType:'normal',leavingPlayerId:'c'},'2026-10-01T18:20:00.000Z');s=completeMatch(s,{scoreA:1,scoreB:2,resultType:'normal',leavingPlayerId:'a'},'2026-10-01T18:40:00.000Z');const a=getPlayerStats(s.matches,'a');assert.equal(a.played,2);assert.equal(a.wins,1);assert.equal(a.losses,1);assert.equal(a.longestWinningStreak,1);assert.equal(a.losingStreak,1);const pair=getPairStats(s.matches,'a','b');assert.equal(pair.played,2);assert.equal(pair.wins,1);const h2h=getHeadToHead(s.matches,'a','d');assert.deepEqual(h2h,{played:2,firstWins:1,secondWins:1,draws:0});});
