import { ChevronLeft, Minus, Plus, Sparkles, Trophy } from 'lucide-react';
import { getPairStats, getPlayerStats, getRoundProgress, getTechnicalStats, type Match, type MatchEvent, type Player, type ResultType, type Session, type Team } from '@/lib/domain';

const nameOf=(players:Player[],id:string)=>players.find(p=>p.id===id)?.nickname||players.find(p=>p.id===id)?.name||'שחקן';
const names=(players:Player[],ids:string[])=>ids.map(id=>nameOf(players,id)).join(' + ');
const formatDate=(value:string)=>new Date(value).toLocaleDateString('he-IL',{day:'numeric',month:'long',year:'numeric'});
const scoreText=(m:Match)=>`${m.scoreA} : ${m.scoreB}`;

export function TeamPanel({team,ids,score,players,onScore}:{team:Team;ids:string[];score:number;players:Player[];onScore:(team:Team,delta:number)=>void}){return <div className={`team-panel ${team.toLowerCase()}`}><span className="team-tag">TEAM {team}</span><div className="team-players">{ids.map(id=><span className="team-player" key={id}><span className="team-player-dot">{nameOf(players,id).slice(0,1)}</span>{nameOf(players,id)}</span>)}</div><div className="score-number" aria-live="polite">{score}</div><div className="score-controls"><button onClick={()=>onScore(team,-1)} aria-label={`הורדת שער לקבוצה ${team}`}><Minus size={23}/></button><button className="score-plus" onClick={()=>onScore(team,1)} aria-label={`הוספת שער לקבוצה ${team}`}><Plus size={26}/></button></div></div>}
export function RoundStatus({session,players}:{session:Session;players:Player[]}){
  const rounds=getRoundProgress(session.matches);
  return <section className="section"><div className="section-head"><h2>סבבים</h2><span className="badge">{rounds.completed.length} הושלמו</span></div><div className="card">
    <p className="small muted">זוג משלים סבב כשהוא מנצח ברצף את כל הצירופים האפשריים של זוג היריבים.</p>
    {rounds.pair&&rounds.beaten>0?<><p><strong>{names(players,rounds.pair)}</strong> · {rounds.beaten} מתוך {rounds.required} צמדי יריבים בדרך לסבב הבא</p><div className="round-opponents">{rounds.opponents.map(opponent=><div className={opponent.beaten?'beaten':''} key={opponent.pair.join('-')}><span>{opponent.beaten?'✓':'○'}</span>{names(players,opponent.pair)}</div>)}</div></>:<p className="small muted">עדיין אין רצף בדרך לסבב הבא.</p>}
    {rounds.completed.length>0&&<div className="round-winners">{rounds.completed.map((round,index)=><div key={round.matchId}><Trophy size={15}/><span>סבב {index+1}: {names(players,round.pair)}</span></div>)}</div>}
  </div></section>;
}
export function GameRow({match,players,onPunchline}:{match:Match;players:Player[];onPunchline:()=>void}){return <div className="game-row"><div className="game-no">{match.sequenceNumber}</div><div className="game-teams"><strong>{names(players,match.lineupBefore.A)}</strong><span>מול {names(players,match.lineupBefore.B)}</span></div><div className="game-score">{scoreText(match)}</div><button className="text-btn" aria-label={`פאנץ׳ למשחק ${match.sequenceNumber}`} onClick={onPunchline}><Sparkles size={16}/></button></div>}
export function SessionRow({session,players,onClick}:{session:Session;players:Player[];onClick:()=>void}){const top=session.playerIds.map(id=>({id,wins:getPlayerStats(session.matches,id).wins})).sort((a,b)=>b.wins-a.wins)[0];return <button className="preset" onClick={onClick} style={{width:'100%',marginBottom:9}}><span><strong>{session.title}</strong><span>{formatDate(session.date)} · {session.matches.length} משחקים · {top&&top.wins?`מוביל: ${nameOf(players,top.id)}`:'ללא משחקים'}</span></span><ChevronLeft size={20}/></button>}
export function SessionSummary({session,players}:{session:Session;players:Player[]}){const stats=session.playerIds.map(id=>getPlayerStats(session.matches,id)).sort((a,b)=>b.wins-a.wins||b.winRate-a.winRate);const pairs=session.playerIds.flatMap((id,i)=>session.playerIds.slice(i+1).map(other=>getPairStats(session.matches,id,other))).filter(p=>p.played).sort((a,b)=>b.winRate-a.winRate||b.wins-a.wins);const technicalKing=[...session.playerIds].map(id=>({id,...getTechnicalStats(session.matches,id)})).sort((a,b)=>b.given-a.given)[0];const streakKing=[...stats].sort((a,b)=>b.longestWinningStreak-a.longestWinningStreak)[0];const biggest=[...session.matches].sort((a,b)=>Math.abs(b.scoreA-b.scoreB)-Math.abs(a.scoreA-a.scoreB))[0];return <section className="section"><div className="section-head"><h2>סיכום הערב</h2><Trophy size={18} color="var(--gold)"/></div><div className="night-awards"><div><span>👑</span><small>מלך הערב</small><strong>{stats[0]?.wins?nameOf(players,stats[0].playerId):'—'}</strong></div><div><span>🤝</span><small>זוג הערב</small><strong>{pairs[0]?names(players,pairs[0].playerIds):'—'}</strong></div><div><span>🥐</span><small>בורקס הערב</small><strong>{technicalKing?.given?nameOf(players,technicalKing.id):'—'}</strong></div><div><span>🔥</span><small>רצף הערב</small><strong>{streakKing?.longestWinningStreak?nameOf(players,streakKing.playerId):'—'}</strong></div></div><div className="summary-grid"><div className="summary-box"><span className="label">הכי הרבה ניצחונות</span><strong>{stats[0]?.wins?nameOf(players,stats[0].playerId):'—'}</strong><span className="small muted">{stats[0]?.wins||0} ניצחונות</span></div><div className="summary-box"><span className="label">הזוג המוביל</span><strong style={{fontSize:16}}>{pairs[0]?names(players,pairs[0].playerIds):'—'}</strong><span className="small muted">{pairs[0]?.wins||0} ניצחונות</span></div><div className="summary-box"><span className="label">משחקים / שערים</span><strong>{session.matches.length} / {session.matches.reduce((n,m)=>n+m.scoreA+m.scoreB,0)}</strong></div><div className="summary-box"><span className="label">הניצחון הכי גדול</span><strong>{biggest?scoreText(biggest):'—'}</strong></div></div><div className="mini-stat-row" style={{marginTop:10}}>{stats.slice(0,3).map((s,i)=><div className="mini-stat" key={s.playerId}><strong>{s.wins}</strong><span>{i===0?'👑 ':''}{nameOf(players,s.playerId)}</span></div>)}</div></section>}
export function resultLabel(type:ResultType){return type==='normal'?'רגיל':type==='penalties'?'פנדלים':'טכני · 3:0'}
export function eventLabel(type:MatchEvent['type']){return ({goal:'גול',own_goal:'גול עצמי',penalty:'פנדל',technical:'גול טכני',funny:'אירוע מצחיק'})[type]}

